### ISSUE TITLE
Fallan los decorados

### ISSUE THREAD

**Issue by nvidiosin** [Victormafire/IsoUnity#16]
Al intentar incluir en el mapa cualquier decorado, el proyecto empieza a lanzar errores y falla

**Comment by nvidiosin** [comment]
![error decoracion](https://cloud.githubusercontent.com/assets/10023451/6830525/8bd3b60c-d31a-11e4-8546-1cf1a1c8147c.jpg)

**Comment by Victormafire** [comment]
Comprueba que en la carpeta Resources exista el archivo IsoSettings.
En su interior hay una propiedad que se llama "defaultTextureScale" es utilizada para escalar todas las decoraciones y corresponder el tamaño del pixel. 
Simplemente debes seleccionar cualquier textura básica del suelo preferiblemente.

**Comment by Victormafire** [comment]
Referenced in #19. This problem will be solved there.
