### ISSUE TITLE
GameEvent.setParameter("par",List<T>)

### ISSUE THREAD

**Issue by Synpheros** [Victormafire/IsoUnity#22]
Hay que implementar la posibilidad de incluir listas List<T> o T[] dentro de un GameEvent.

**Comment by Victormafire** [comment]
Muy interesante, voy a ponerme con ello.

**Comment by Victormafire** [comment]
Al final se puede meter List<object>, siendo la opción más generica y soportando desde tipos básicos hasta UnityEngine.Object.
