### ISSUE TITLE
Al cambiar de escena y volver a la inicial no se guardan los Paints

### ISSUE THREAD

**Issue by nvidiosin** [Victormafire/IsoUnity#23]
Creas una nueva escena, dibujas un mapa 8x8 y lo pintas, guardas la escena y el juego y cierras el programa. Vuelves a abrir el programa o cambias de escena y vuelves a la del mapa creado y la pintura ha desaparecido.

**Comment by Victormafire** [comment]
En realidad ya me había dado cuenta del error hace una semana y lo había resuelto, mañana os lo subo corregido junto con algunas actualizaciones.
