### ISSUE TITLE
Cancelar movimientos

### ISSUE THREAD

**Issue by nvidiosin** [Victormafire/IsoUnity#25]
Es posible que esté relacionado con el issue "Move Stop".

Cuando tratamos de encadenar movimientos el problema es que invoca un movimiento sin terminar otro y cuando termina el que estaba ejecutandose terminan los dos.
Hay alguna forma de cancerlar un movimiento para cancerla el otro?
O que el API permite encolar movimientos, de forma que al terminar uno ejecute el siguiente.

**Comment by Victormafire** [comment]
Referenced in #20
