### ISSUE TITLE
First time you try to move to a non-accessible cell, the game crashes

### ISSUE THREAD

**Issue by federicopeinado** [Victormafire/IsoUnity#31]
Hay una manera de evitarlo, que es pulsar la primera vez sobre una casilla que no te puedas mover NADA MÁS ARRANCAR EL JUEGO, se queda como congelado dos segundos... pero ya no peta nunca más (???)

**Comment by Victormafire** [comment]
@nvidiosin y yo estudiamos por qué podía ocurrir esto y estoy casi seguro de que el A* examina todo el mapa con la intención de encontrar el camino y por eso se bloquea. Podemos hacer el A* más inteligente o limitarlo a un máximo número de expansiones (por ejemplo, a las visibles en la pantalla) o a unas décimas de segundo.
