### ISSUE TITLE
Characters should be able to "turn" toward a direction, although they were not able to "move" there

### ISSUE THREAD

**Issue by federicopeinado** [Victormafire/IsoUnity#40]
Maybe this could be a checkeable option?

**Comment by Victormafire** [comment]
Yes, I've been thinking in this and this should be avaliable even from secuences to give them more sense when looking things (and not having to make strange paths to get in the desired look).

I'll add a new property into the entity and mover to change the looking direction and add a new gameevent to change it also from secuences.

**Comment by federicopeinado** [comment]
Thanks! ;-)
