### ISSUE TITLE
It should be useful to change keyboard controls (adding WSAD for movement, for instance)

### ISSUE THREAD

**Issue by federicopeinado** [Victormafire/IsoUnity#41]
Maybe it is just a question of being sure that IsoUnity uses "standard input" from Unity (up, down, right, left...) and then changing whatever you want directly from Unity... not sure :-P

**Comment by Victormafire** [comment]
Since the controller uses Input from unity, any changes performed in Input will impact over Controller. Movement can be performed using WSAD of course, and even from a JoyPad or whatever.

**Comment by Victormafire** [comment]
I'll close this in case this is solved, re open if neccesary :)
