### ISSUE TITLE
Method: Turn direction

### ISSUE THREAD

**Issue by nvidiosin** [Victormafire/IsoUnity#50]
Allow users to use the Entity´s method TurnDirection like
Entity.turnDirection(Direction);

Ty guys

**Comment by Victormafire** [comment]
This is implemented since https://github.com/Victormafire/IsoUnity/releases/tag/v0.3.
The way it should be used can be accesed by three ways:

- From property:
```
Entity.mover.direction / Entity.GetComponent<Mover>().direction
```
- From method:
```
Entity.mover.switchDirection(direction) / Entity.GetComponent<Mover>().switchDirection(direction)
```
- From GameEvent:
```
GameEvent ge = GameEvent.CreateInstance<GameEvent> ();
	ge.Name = "turn";
	ge.setParameter ("entity", entity);
	ge.setParameter ("direction", direction);
	Game.main.enqueueEvent (ge);
```
